- hosts:
    - awsswarmmanager
  tasks:
    - name: Update the front_end_testing service
      shell: docker service update --force --image knoxie2/front_end_app_testing:latest staging_stack_front_end
