pipeline {
    environment {
        testingregistry = "knoxie2/front_end_app_testing"
        productionregistry = "knoxie2/front_end_app"
        registryCredential = 'knoxie2'
        dockerImage = ''
        HOME = '/tmp'

    } 
    agent any
    stages {
        stage('Building image for Testting') {
          when {
              branch 'development'
            }
            steps {
              script {
                dockerImage = docker.build testingregistry + ":latest"
              }
            }
        }
        
        stage('Running Unit Tests') {
          when {
              branch 'development'
            }
            steps {
              script {
                docker.image("knoxie2/front_end_app_testing:latest").inside("""--entrypoint=''""") {
                  sh 'dotnet --version'
                  sh 'cd src/FrontEndApp.Unittests'
                  sh 'dotnet test --logger "trx;LogFileName=unit_tests.xml"'
                }
              }
            }
        }
        
        stage('Building image for Production') {
          when {
              branch 'staging'
            }
            steps {
              script {
                dockerImage = docker.build (productionregistry + ":latest", "./deployment") 
              }
            }
        }
        
        stage('Push Image to Ducker Hub') {
           when {
              not {
                branch 'main'
              }
               not {
                branch 'development'
              }
            }
            steps{    
              script {
                docker.withRegistry( '', registryCredential ) {
                  dockerImage.push()
                }
              }
            }
        }

        stage('Remove Unused Testing docker image') {
           when {
              branch 'development'
            }
            steps{
              sh "docker rmi $testingregistry:latest" 
            }
        }

        stage('Remove Unused Production docker image') {
           when {
              branch 'staging'
            }
            steps{
              sh "docker rmi $productionregistry:latest"
            }
        }

        stage('Deploy to Staging environment') {
          when {
              branch 'staging'
            }
            steps{
              // sh './deployment/scripts/testing-deployment.sh'
              ansiblePlaybook(credentialsId: 'root', playbook: './playbooks/deploy-for-staging.yml',inventory: "${HOSTS}")
            }
        }
         stage('Deploy to Production environment') {
          when {
              branch 'main'
            }
            steps{
              ansiblePlaybook(credentialsId: 'root', playbook: './playbooks/deploy-for-production.yml',inventory: "${HOSTS}")

            }
        }
    }
     post { 
        always { 
            cleanWs()
        }
    }
}
